title: Neuro Interface Lab
description: Research, neurotechnology, interfaces, and open science.
author: Neuro Interface Lab
lang: en
url: "https://neuro-interface-lab.github.io"
baseurl: ""
logo: "/assets/logo/neuro-interfaces-logo.png"
markdown: kramdown
permalink: /:slug
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: "light"
  appearance_toggle: true
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: false
  show_old_projects: false
  show_misc_list: false
  home:
    title_projects: Explore
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll/scholar

scholar:
  style: apa
  locale: en
  source: ./_data
  bibliography: publications.bib
  sort_by: year
  order: descending
  group_by: year
  group_order: descending
